Feat: `default` file to avoid credentials commits
moio/raspberry-openvpn-gateway pull request #10
Opened 2016-12-23 11:42 UTC by mbologna

2016-12-28 13:38 UTC, moio commented
Please add a description to this PR, the effect is not clear from the title. Also please modify the README to update instructions for new users.

2017-01-02 07:13 UTC, moio requested changes

2017-01-02 07:13 UTC, moio commented on .gitignore
> +pillar/config.sls
Last question: why is this here? This PR does not seem to affect this file at all. I guess this line should just be removed.

2017-01-02 08:52 UTC, mbologna reviewed
Why do we need .default files in openvpn config on raspberry side?

2017-01-02 08:55 UTC, mbologna commented on .gitignore
> +pillar/config.sls
You're right. Removed.

2017-06-23 08:36 UTC, moio approved these changes

2017-06-23 08:37 UTC, merged