Mumble
moio/raspberry-openvpn-gateway pull request #11
Opened 2016-12-23 16:21 UTC by mbologna

Without this patch, Mumble will forcily switch
to TCP-mode after not receiving UDP packets.

2016-12-28 13:42 UTC, moio requested changes

2016-12-28 13:42 UTC, moio commented on .gitignore
> +pillar/config.sls
Please base your PR on current master rather than other PRs unless necessary, this makes it easier for reviewers to accept individually.

2016-12-28 13:42 UTC, moio commented on salt/ufw/lib_ufw/user.rules
> +-A ufw-before-input -i tun0 -p udp --sport 64738 -j ACCEPT
Code and comment do not seem to agree - comment says `tcp` and code `udp`. Is this expected? Why is this rule needed and what is its effect in detail?

2016-12-28 14:00 UTC, mbologna commented on .gitignore
> +pillar/config.sls
You're right. Rebased.

2016-12-28 14:01 UTC, mbologna commented on salt/ufw/lib_ufw/user.rules
> +-A ufw-before-input -i tun0 -p udp --sport 64738 -j ACCEPT
You're right. I added description in PR text.

2017-01-02 07:22 UTC, moio approved these changes

2017-01-02 07:24 UTC, moio commented
I am merging this now, thanks for having fixed this (I also noticed "something strange" but never took the time to really go into the tiny details!)

I also wonder if, in future, some more general solution could be feasible (eg. allow any incoming UDP traffic provided it was "client initiated", to mimick behavior on the TCP side).

:+1: :beers: !

2017-01-02 07:25 UTC, merged