Feat: Prefer ed25519 ssh keys over rsa
moio/raspberry-openvpn-gateway pull request #13
Opened 2016-12-27 10:41 UTC by mbologna

2016-12-28 13:45 UTC, moio requested changes

2016-12-28 13:45 UTC, moio commented on salt/sshd/init.sls
> +        ssh-keygen -t ed25519 -f ssh_host_ed25519_key < /dev/null
Can you include in the commit comment/PR text a pointer to some security discussions on why this should be preferrable?

2016-12-28 13:47 UTC, mbologna commented on salt/sshd/init.sls
> +        ssh-keygen -t ed25519 -f ssh_host_ed25519_key < /dev/null
I followed the URL already present in README.md:
https://stribika.github.io/2015/01/04/secure-secure-shell.html

2017-01-02 07:27 UTC, moio approved these changes

2017-01-02 07:28 UTC, merged