Feat: harden sysctl with secure default values
moio/raspberry-openvpn-gateway pull request #15
Opened 2016-12-27 10:47 UTC by mbologna

2016-12-28 13:47 UTC, moio requested changes

2016-12-28 13:47 UTC, moio commented on salt/ufw/etc_ufw/sysctl.conf
> +#net/ipv4/icmp_echo_ignore_all = 1
Is this commented out intentionally?

2016-12-28 13:47 UTC, moio commented on salt/ufw/etc_ufw/sysctl.conf
> +# Performance Recommended Settings:
Are those settings related to security? Why should they be preferred?

2016-12-30 10:01 UTC, mbologna commented on salt/ufw/etc_ufw/sysctl.conf
> +#net/ipv4/icmp_echo_ignore_all = 1
Yes, at line 49 we are allowing ICMP echo. However, if someone wants to blocka all echo should uncomment this line.

2016-12-30 10:03 UTC, mbologna commented on salt/ufw/etc_ufw/sysctl.conf
> +# Performance Recommended Settings:
The following settings are not related to security: they are more directed towards performance: 
https://www.cyberciti.biz/faq/linux-tcp-tuning/

Do you think it's a good idea to separate these settings into another sysctl-sls related file?

2017-01-02 07:31 UTC, moio commented on salt/ufw/etc_ufw/sysctl.conf
> +#net/ipv4/icmp_echo_ignore_all = 1
Then please either remove this line or comment it inline.

2017-01-02 07:37 UTC, moio commented on salt/ufw/etc_ufw/sysctl.conf
> +# Performance Recommended Settings:
No, a separate file is not really necessary.

It is more of a matter of titles - commit and PR titles. This PR has "security" in its title, so this change does not really belong here.

Please either:
 - change the PR title to something more generic (like "sysct default improvements") and distinguish security and performance settings in commit messages, or
 - create a separate PR for performance settings

Furthermore, do you have any indication as to why Jessie defaults are inadequate in this case, or any measurable benefit from these settings? I would not want to maintain a different set of settings than the defaults unless it is beneficial.

2017-01-02 09:12 UTC, mbologna commented on salt/ufw/etc_ufw/sysctl.conf
> +# Performance Recommended Settings:
This contains the same adjustments and claims to be a reference among tweakers: http://www.slideshare.net/AmazonWebServices/pfc306-performance-tuning-amazon-ec2-instances-aws-reinvent-2014

2017-01-04 12:35 UTC, moio commented on salt/ufw/etc_ufw/sysctl.conf
> +# Performance Recommended Settings:
This is 1) specific to AWS 2) "take only when prescribed from performance engineer" 3) "best before 2015" and most importantly 4) unlikely to get any benefit in this scenario.

I am not going to merge the performance part, please remove it from this PR.

2017-05-24 09:33 UTC, mbologna commented on salt/ufw/etc_ufw/sysctl.conf
> +# Performance Recommended Settings:
Performance part has been removed. Only the security part is still present.

2017-06-23 08:23 UTC, moio approved these changes

2017-06-23 08:24 UTC, merged