Feat: set hostname properly
moio/raspberry-openvpn-gateway pull request #16
Opened 2016-12-27 10:52 UTC by mbologna

2016-12-28 13:49 UTC, moio requested changes

2016-12-28 13:49 UTC, moio commented on pillar/config.sls
> +hostname: rpi
Default hostname should be raspberrypi

2016-12-28 13:49 UTC, moio commented on pillar/config.sls
> +{%- set dnsdomainname = "michelebologna.net" %}
Why is this needed and why is it in set form?

2016-12-28 13:53 UTC, mbologna commented on pillar/config.sls
> +{%- set dnsdomainname = "michelebologna.net" %}
This is in a `set` form to use dnsdomainname in other variables (e.g. https://github.com/moio/raspberry-openvpn-gateway/pull/17/commits/c53ad618bb4362d8286f427c6db0c9f8301a9d97)

2017-05-16 07:27 UTC, moio commented on pillar/config.sls
> +{%- set dnsdomainname = "michelebologna.net" %}
Please try using a plain pillar variable, thanks!

2017-05-24 09:34 UTC, mbologna commented on pillar/config.sls
> +{%- set dnsdomainname = "michelebologna.net" %}
Done!

2017-06-23 07:19 UTC, moio approved these changes

2017-06-23 07:22 UTC, merged